### ISSUE TITLE
32-Bit .deb Thinks it's amd64.

### ISSUE THREAD

**Issue by ThePillenwerfer** [oOthkOo/whatsapp-desktop#11]
### System details

* OS: Debian 10 32-bit
* App Version: 0.5.1 
* If Linux, Desktop Environment: Mate
### Expected behavior

To install.

### Actual behavior

Error that the package is 64-bit

### Step to reproduce the behavior

Try to install `whatsapp-desktop-ia32.deb` on a 32-bit system.

The `control` file contains the line
```
Architecture: amd64
```

If the contents of `opt` are manually extracted the binary works.

**Comment by oOthkOo** [comment]
Fixed ;-)
