### ISSUE TITLE
please update the icons?

### ISSUE THREAD

**Issue by dbpm1** [oOthkOo/whatsapp-desktop#12]
in the windows taskbar the current icon looks aliased.. I attached an gz file with separate ico files and a ico group!

[icons.tar.gz](https://github.com/oOthkOo/whatsapp-desktop/files/6627538/icons.tar.gz)

![image](https://user-images.githubusercontent.com/82009615/121445636-3c470080-c968-11eb-98f7-cfb67bcae70e.png)
icon on the left is the official client on my business account with the shortcut modified to look like its the real business and on the right the unofficial client which doesn't look that good ;)

**Comment by dbpm1** [comment]
went the extra mile and also made the business icon pack.. if possible consider an option in the settings to change the icon or maybe a switch like discussed here: https://stackoverflow.com/questions/31529772/how-to-set-app-icon-for-electron-atom-shell-app

[business.tar.gz](https://github.com/oOthkOo/whatsapp-desktop/files/6627595/business.tar.gz)

**Comment by oOthkOo** [comment]
Hi,

Windows Icon updated.

**Comment by dbpm1** [comment]
Thanks!
