### ISSUE TITLE
Inorrect timestamp

### ISSUE THREAD

**Issue by jarayama** [oOthkOo/whatsapp-desktop#15]
* OS: Windows 11 beta
* App Version: latest

The timestamp on the messages is incorrect, it shows one more hour. I was looking for this issue and found a couple of people having this problem with the Whatsapp web version and using an old Chrome version (fixed with updated version), so I think the problem is on the electron-chromium side-

Thanks. 

![image](https://user-images.githubusercontent.com/7914941/129926986-72fd7730-c0cc-47df-ab7c-8f0fb19032f8.png)

**Comment by oOthkOo** [comment]
Hello,

Electron was updated to **17.0.0**.

Enjoy ;-)
