### ISSUE TITLE
Last release > 1 year ago

### ISSUE THREAD

**Issue by mjeveritt** [oOthkOo/whatsapp-desktop#22]
Whilst the app is certainly still quite functional, there have clearly been updates to Electron, and probably other relevant frameworks.

Last release was now over a year ago, and I'm sure the update would be worthwhile even assuming there are no security issues/etc.

**Comment by oOthkOo** [comment]
A new version **0.5.2** of the application is available.
Electron has been updated to version **17.0.0**.

Enjoy :-)
